Upgrade go to 1.3.
The cross-cgo.patch file is deleted, because cgo in cross builds is
fixed in 1.3.
http://golang.org/doc/go1.3#gocmd
https://code.google.com/p/go/issues/detail?id=4714#c28

The download page moved to http://golang.org/dl/. golang.org has https,
but the Wget 1.13.4 from Ubuntu 12.04 doesn't have SNI support, which
appears to be necessary:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=653267

--2014-07-17 17:20:11--  https://golang.org/dl/go1.3.src.tar.gz
Resolving golang.org (golang.org)... 74.125.20.141, 2607:f8b0:400e:c01::8d
Connecting to golang.org (golang.org)|74.125.20.141|:443... connected.
ERROR: no certificate subject alternative name matches
        requested host name `golang.org'.
To connect to golang.org insecurely, use `--no-check-certificate'.