Update WEBRTC_TAG to branch-heads/52.
Set to f336982 as in https://github.com/keroserene/go-webrtc/issues/39.

Actually, at this moment, branch-heads/52 is 3 commits ahead (ca7fe7e)
of where it was at the time of GitHub #39.

I had to change "gyp_webrtc" to "gyp_webrtc.py" as the former is no
longer executable:
	+ webrtc/build/gyp_webrtc
	bash: line 288: webrtc/build/gyp_webrtc: Permission denied
"gyp_webrtc" just does:
	execfile(__file__ + '.py')

I added "werror=" to GYP_DEFINES because of this warning that stopped
the build by being treated as an error:
	../../webrtc/voice_engine/channel.cc: In member function 'void webrtc::voe::Channel::Demultiplex(const int16_t*, int, size_t, size_t)':
	../../webrtc/voice_engine/channel.cc:2954:13: error: '*((void*)& codec +44)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
	   CodecInst codec;
		     ^
	../../webrtc/voice_engine/channel.cc:2954:13: error: '*((void*)& codec +36)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
	cc1plus: all warnings being treated as errors
I suspect that more recent versions of GCC than our current 5.1.0 don't
raise a warning here.

I changed the test target name from
libjingle_peerconnection_unittest.isolated to
peerconnection_unittests.isolated. It seems that libjingle is going to
stop existing as a separate concern. Anyway, the old target name doesn't
exist:
	+ ninja -C out/Release libjingle_peerconnection_unittest.isolated
	ninja: Entering directory `out/Release'
	ninja: error: unknown target 'libjingle_peerconnection_unittest.isolated'